name: arkenergyapp
description: "Automation Project"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  provider: ^6.0.0
  intl: ^0.19.0
  toastification: ^2.3.0
  http: ^1.2.2
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
